name: Blacksmith Runner Tests

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache node modules and Playwright browsers
        uses: useblacksmith/cache@v5.1.1
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-bun
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: bun install

      - name: Check Cache Playwright browsers
        run: |
          if [ -d ~/.cache/ms-playwright ]; then
            du -hs ~/.cache/ms-playwright/*
          else
            echo "Playwright cache directory does not exist."
          fi

      # - name: Install Microsoft Edge (if not cached)
      #   run: |
      #     if [ ! -d ~/.cache/ms-playwright/msedge ]; then
      #       bun playwright install msedge
      #     fi

      - name: Install Playwright browsers (Firefox only if not cached)
        run: |
          if [ ! -d ~/.cache/ms-playwright/firefox ]; then
            bun playwright install firefox
          fi

      - name: Run Playwright tests
        run: bun playwright test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
