name: Playwright Tests

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache node modules and Playwright browsers
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers (Firefox only if not cached)
        run: |
          if [ ! -d ~/.cache/ms-playwright/firefox ]; then
            npx playwright install firefox
          fi

      - name: Run Playwright tests
        run: npx playwright test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
