name: Playwright Tests

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache node modules and Playwright browsers
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-bun
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: bun install

      - name: Check Cache Playwright browsers
        run: |
          if [ -d ~/.cache/ms-playwright ]; then
            du -hs ~/.cache/ms-playwright/*
          else
            echo "Playwright cache directory does not exist."
          fi

      - name: Install Playwright browsers (Firefox only if not cached)
        run: |
          if [ ! -d ~/.cache/ms-playwright/firefox ]; then
            bun playwright install firefox
          fi

      - name: Delete products.json
        run: rm -f products.json

      - name: Download products.json from artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: products-json
          path: .
        continue-on-error: true

      - name: Check if products.json exists
        id: check_products_json
        run: |
          if [ ! -f products.json ]; then
            echo "products.json does not exist. Creating an empty file."
            echo "[]" > products.json
          fi

      - name: Run Playwright tests
        run: bun playwright test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Upload products.json to artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: products-json
          path: products.json
