name: Processor Price Tracker

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allow manual triggering

jobs:
  track-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache node modules and Playwright browsers
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-bun
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: bun install

      - name: Check Cache Playwright browsers
        run: |
          if [ -d ~/.cache/ms-playwright ]; then
            du -hs ~/.cache/ms-playwright/*
          else
            echo "Playwright cache directory does not exist."
          fi

      - name: Install Playwright browsers (Firefox only if not cached)
        run: |
          if [ ! -d ~/.cache/ms-playwright/firefox ]; then
            bun playwright install firefox
          fi

      - name: Download latest artifact (if exists)
        uses: actions/download-artifact@v4.1.8
        with:
          name: processor-db
          path: ./
          if-no-files-found: warn

      - name: Display structure of downloaded files
        run: ls -R

      - name: Run processor test
        run: bun playwright test tests/procieamd9000series.spec.js

      - name: Upload processor.db as artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: processor-db
          path: processor.db
          retention-days: 7